;              
CREATE USER IF NOT EXISTS "SA" SALT '4f0ffd969fdbe4af' HASH '624e9a23d155c60a137322aeb4d9ea37d23895039b85bbe630acdfa184365e7d' ADMIN;          
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_999FA83F_022B_40EE_B6C2_9D9C887B8CF4" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1E1872CA_3067_4E88_9A56_8E6E24790E68" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_BA2D9CE4_172A_4DD4_BCF4_5FDEBB1A1342" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9A959CD3_DCDC_4610_BABA_93F94D5033C4" START WITH 3 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D6614833_1027_46F7_808D_476CA35E43FE" START WITH 4 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C837785A_D72A_4820_B3DA_AF6140A1DC8A" START WITH 4 BELONGS_TO_TABLE; 
CREATE MEMORY TABLE "PUBLIC"."CURSO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_1E1872CA_3067_4E88_9A56_8E6E24790E68" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1E1872CA_3067_4E88_9A56_8E6E24790E68",
    "INSTITUICAO_DE_ENSINO" VARCHAR(255),
    "NOME" VARCHAR(255),
    "PERIODO" INTEGER,
    "SIGLA" INTEGER
);              
ALTER TABLE "PUBLIC"."CURSO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CURSO;    
INSERT INTO "PUBLIC"."CURSO" VALUES
(1, 'UFS', 'Engenharia de Computacao', 6, 1);              
CREATE MEMORY TABLE "PUBLIC"."CURSO_DISCIPLINA"(
    "CURSO_ID" INTEGER NOT NULL,
    "DISCIPLINA_ID" INTEGER NOT NULL
);      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.CURSO_DISCIPLINA;         
INSERT INTO "PUBLIC"."CURSO_DISCIPLINA" VALUES
(1, 1),
(1, 2),
(1, 3);         
CREATE MEMORY TABLE "PUBLIC"."DISCIPLINA"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D6614833_1027_46F7_808D_476CA35E43FE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D6614833_1027_46F7_808D_476CA35E43FE",
    "CODIGO" VARCHAR(255),
    "CREDITOS" INTEGER,
    "NOME" VARCHAR(255),
    "DOCENTE_ID" INTEGER
);  
ALTER TABLE "PUBLIC"."DISCIPLINA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_32" PRIMARY KEY("ID");   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.DISCIPLINA;               
INSERT INTO "PUBLIC"."DISCIPLINA" VALUES
(1, 'IA', 4, 'Inteligencia Artificial', 1),
(2, 'ES', 8, 'Eng Software', 2),
(3, 'PP', 4, 'Programacao Paralela', 2); 
CREATE MEMORY TABLE "PUBLIC"."DOCENTE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_9A959CD3_DCDC_4610_BABA_93F94D5033C4" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9A959CD3_DCDC_4610_BABA_93F94D5033C4",
    "NOME" VARCHAR(255),
    "TURNO" INTEGER
);             
ALTER TABLE "PUBLIC"."DOCENTE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");       
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.DOCENTE;  
INSERT INTO "PUBLIC"."DOCENTE" VALUES
(1, 'Carlos Alberto', 1),
(2, 'Leonardo', 2);            
CREATE MEMORY TABLE "PUBLIC"."GRADE"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_BA2D9CE4_172A_4DD4_BCF4_5FDEBB1A1342" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_BA2D9CE4_172A_4DD4_BCF4_5FDEBB1A1342",
    "HORA_CRIACAO" TIMESTAMP,
    "NOME" VARCHAR(255),
    "USUARIO_ID" INTEGER
);            
ALTER TABLE "PUBLIC"."GRADE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.GRADE;    
INSERT INTO "PUBLIC"."GRADE" VALUES
(1, TIMESTAMP '2022-05-03 09:43:36.902', 'Grade UFS EC', 1);               
CREATE MEMORY TABLE "PUBLIC"."GRADE_DISCIPLINA"(
    "GRADE_ID" INTEGER NOT NULL,
    "DISCIPLINA_ID" INTEGER NOT NULL
);      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.GRADE_DISCIPLINA;         
INSERT INTO "PUBLIC"."GRADE_DISCIPLINA" VALUES
(1, 1),
(1, 2),
(1, 3);         
CREATE MEMORY TABLE "PUBLIC"."GRADE_DOCENTE"(
    "GRADE_ID" INTEGER NOT NULL,
    "DOCENTE_ID" INTEGER NOT NULL
);            
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.GRADE_DOCENTE;            
INSERT INTO "PUBLIC"."GRADE_DOCENTE" VALUES
(1, 1),
(1, 2);    
CREATE MEMORY TABLE "PUBLIC"."PERFIS"(
    "USUARIO_ID" INTEGER NOT NULL,
    "PERFIS" INTEGER
);              
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PERFIS;   
INSERT INTO "PUBLIC"."PERFIS" VALUES
(1, 2);   
CREATE MEMORY TABLE "PUBLIC"."RESTRICAO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C837785A_D72A_4820_B3DA_AF6140A1DC8A" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C837785A_D72A_4820_B3DA_AF6140A1DC8A",
    "DIA_DA_SEMANA" INTEGER,
    "NOME" VARCHAR(255),
    "DOCENTE_ID" INTEGER
);         
ALTER TABLE "PUBLIC"."RESTRICAO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_38" PRIMARY KEY("ID");    
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.RESTRICAO;
INSERT INTO "PUBLIC"."RESTRICAO" VALUES
(1, 2, 'Restr 1', 1),
(2, 3, STRINGDECODE('Ter\u00e7a pode'), 1),
(3, 4, 'Restr 3', 2);
CREATE MEMORY TABLE "PUBLIC"."RESTRICAO_INDISPONIBILIDADE"(
    "RAZAO_INDISPONIVEL" VARCHAR(255),
    "ID" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."RESTRICAO_INDISPONIBILIDADE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");   
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.RESTRICAO_INDISPONIBILIDADE;              
INSERT INTO "PUBLIC"."RESTRICAO_INDISPONIBILIDADE" VALUES
(STRINGDECODE('N\u00e3o pode dar aula de noite'), 1),
(STRINGDECODE('N\u00e3o pode dar aula de manha'), 3);          
CREATE MEMORY TABLE "PUBLIC"."RESTRICAO_PREFERENCIA"(
    "PRIORIDADE" INTEGER,
    "ID" INTEGER NOT NULL
);   
ALTER TABLE "PUBLIC"."RESTRICAO_PREFERENCIA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RESTRICAO_PREFERENCIA;    
INSERT INTO "PUBLIC"."RESTRICAO_PREFERENCIA" VALUES
(5, 2);    
CREATE MEMORY TABLE "PUBLIC"."USUARIO"(
    "ID" INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_999FA83F_022B_40EE_B6C2_9D9C887B8CF4" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_999FA83F_022B_40EE_B6C2_9D9C887B8CF4",
    "EMAIL" VARCHAR(255),
    "NOME" VARCHAR(255),
    "SENHA" VARCHAR(255)
);              
ALTER TABLE "PUBLIC"."USUARIO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO;  
INSERT INTO "PUBLIC"."USUARIO" VALUES
(1, 'juan@teste.com', 'juan', '$2a$10$vxQ6MXGGyMD4mc7FG.CuGu4PPT1s1DW7Zmq8s79bUntGZgxH/KdYW');           
ALTER TABLE "PUBLIC"."RESTRICAO" ADD CONSTRAINT "PUBLIC"."FKS0PJBM17O71IJWEDXLTRQRVAS" FOREIGN KEY("DOCENTE_ID") REFERENCES "PUBLIC"."DOCENTE"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."PERFIS" ADD CONSTRAINT "PUBLIC"."FKISO72AJMKK36LW7DQJVA1H8HL" FOREIGN KEY("USUARIO_ID") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."RESTRICAO_PREFERENCIA" ADD CONSTRAINT "PUBLIC"."FKPL89JR0MIAHSOMQQR91EGAX8" FOREIGN KEY("ID") REFERENCES "PUBLIC"."RESTRICAO"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."CURSO_DISCIPLINA" ADD CONSTRAINT "PUBLIC"."FKR7REUO2YB00HP5WBMESIOINLD" FOREIGN KEY("DISCIPLINA_ID") REFERENCES "PUBLIC"."DISCIPLINA"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."RESTRICAO_INDISPONIBILIDADE" ADD CONSTRAINT "PUBLIC"."FK7ESB0PQ4BVNJU4A5D5FHCOL83" FOREIGN KEY("ID") REFERENCES "PUBLIC"."RESTRICAO"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."GRADE_DOCENTE" ADD CONSTRAINT "PUBLIC"."FKOPHF0LVDVSKTDBA3FA5URUMOB" FOREIGN KEY("DOCENTE_ID") REFERENCES "PUBLIC"."DOCENTE"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."GRADE_DISCIPLINA" ADD CONSTRAINT "PUBLIC"."FK1ICHE3R89U12PHDTOW80WUVQE" FOREIGN KEY("DISCIPLINA_ID") REFERENCES "PUBLIC"."DISCIPLINA"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."GRADE_DISCIPLINA" ADD CONSTRAINT "PUBLIC"."FK80G6L37LMOA2TIBTBDYAXSW3M" FOREIGN KEY("GRADE_ID") REFERENCES "PUBLIC"."GRADE"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."CURSO_DISCIPLINA" ADD CONSTRAINT "PUBLIC"."FKC95RLU26GGUHO8XA8AMQ8JAJQ" FOREIGN KEY("CURSO_ID") REFERENCES "PUBLIC"."CURSO"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."GRADE" ADD CONSTRAINT "PUBLIC"."FK5LIVVV76DWKLTBVWBTRGTH8LI" FOREIGN KEY("USUARIO_ID") REFERENCES "PUBLIC"."USUARIO"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."DISCIPLINA" ADD CONSTRAINT "PUBLIC"."FKACFEF7809ENX5VDQUN2QKY13R" FOREIGN KEY("DOCENTE_ID") REFERENCES "PUBLIC"."DOCENTE"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."GRADE_DOCENTE" ADD CONSTRAINT "PUBLIC"."FKECX60OEDFFOIOEWD32PYHIXTS" FOREIGN KEY("GRADE_ID") REFERENCES "PUBLIC"."GRADE"("ID") NOCHECK;  
